#!/bin/bash
# dLNk IDE - Release Script
# Creates a complete release package

set -e

echo "📦 dLNk IDE - Release Script"
echo "============================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/vscode-fork"
DIST_DIR="$PROJECT_ROOT/dist"
RELEASE_DIR="$PROJECT_ROOT/releases"
VERSION=$(node -p "require('$BUILD_DIR/build-system/build/package.json').version" 2>/dev/null || echo "1.0.0")
DATE=$(date +%Y%m%d)

echo "📁 Project Root: $PROJECT_ROOT"
echo "🏷️  Version: $VERSION"
echo "📅 Date: $DATE"
echo ""

# Create release directory
RELEASE_VERSION_DIR="$RELEASE_DIR/v$VERSION"
mkdir -p "$RELEASE_VERSION_DIR"
echo -e "${GREEN}✅ Release directory created: $RELEASE_VERSION_DIR${NC}"
echo ""

# Step 1: Bundle Extension
echo "🔌 Step 1: Bundling Extension..."
if [ -f "$SCRIPT_DIR/bundle-extension.sh" ]; then
    bash "$SCRIPT_DIR/bundle-extension.sh"
else
    echo -e "${YELLOW}⚠️  bundle-extension.sh not found, skipping${NC}"
fi
echo ""

# Step 2: Build All Platforms
echo "🏗️  Step 2: Building for all platforms..."
if [ -f "$SCRIPT_DIR/build-all.sh" ]; then
    bash "$SCRIPT_DIR/build-all.sh"
else
    echo -e "${YELLOW}⚠️  build-all.sh not found, building manually${NC}"
    cd "$BUILD_DIR/build-system/build"
    npm install
    npm run build:all 2>/dev/null || echo "Build completed with warnings"
fi
echo ""

# Step 3: Copy artifacts to release directory
echo "📋 Step 3: Copying artifacts..."
if [ -d "$DIST_DIR" ]; then
    cp -r "$DIST_DIR"/* "$RELEASE_VERSION_DIR/" 2>/dev/null || true
    echo -e "${GREEN}✅ Artifacts copied${NC}"
else
    echo -e "${YELLOW}⚠️  Dist directory not found${NC}"
fi
echo ""

# Step 4: Generate checksums
echo "🔐 Step 4: Generating checksums..."
cd "$RELEASE_VERSION_DIR"
if ls *.exe *.dmg *.AppImage *.deb *.rpm *.zip *.tar.gz 2>/dev/null; then
    sha256sum *.exe *.dmg *.AppImage *.deb *.rpm *.zip *.tar.gz 2>/dev/null > SHA256SUMS.txt || true
    echo -e "${GREEN}✅ Checksums generated${NC}"
else
    echo -e "${YELLOW}⚠️  No artifacts found for checksum${NC}"
fi
echo ""

# Step 5: Create release notes
echo "📝 Step 5: Creating release notes..."
cat > "$RELEASE_VERSION_DIR/RELEASE_NOTES.md" << EOF
# dLNk IDE v$VERSION Release Notes

**Release Date:** $(date +%Y-%m-%d)

## Downloads

### Windows
- \`dLNk-IDE-$VERSION-win-x64.exe\` - Windows x64 Installer
- \`dLNk-IDE-$VERSION-win-ia32.exe\` - Windows x86 Installer
- \`dLNk-IDE-$VERSION-win-x64.zip\` - Windows x64 Portable

### macOS
- \`dLNk-IDE-$VERSION-mac-x64.dmg\` - macOS Intel
- \`dLNk-IDE-$VERSION-mac-arm64.dmg\` - macOS Apple Silicon

### Linux
- \`dLNk-IDE-$VERSION-linux-x64.AppImage\` - AppImage (Universal)
- \`dLNk-IDE-$VERSION-linux-x64.deb\` - Debian/Ubuntu
- \`dLNk-IDE-$VERSION-linux-x64.rpm\` - Fedora/RHEL
- \`dLNk-IDE-$VERSION-linux-x64.tar.gz\` - Portable

## What's New

- AI-powered code completion
- Integrated AI chat panel
- Multi-provider AI support (Antigravity, OpenAI, Gemini, etc.)
- License management system
- Custom dLNk branding and theme
- Cross-platform support

## Installation

### Windows
1. Download the .exe installer
2. Run the installer
3. Follow the installation wizard

### macOS
1. Download the .dmg file
2. Open the DMG
3. Drag dLNk IDE to Applications

### Linux
**AppImage:**
\`\`\`bash
chmod +x dLNk-IDE-*.AppImage
./dLNk-IDE-*.AppImage
\`\`\`

**Debian/Ubuntu:**
\`\`\`bash
sudo dpkg -i dLNk-IDE-*.deb
\`\`\`

**Fedora/RHEL:**
\`\`\`bash
sudo rpm -i dLNk-IDE-*.rpm
\`\`\`

## Verification

Verify downloads using SHA256SUMS.txt:
\`\`\`bash
sha256sum -c SHA256SUMS.txt
\`\`\`

## Support

- GitHub Issues: https://github.com/dlnk/dlnk-ide/issues
- Telegram: @dlnk_support
- Email: support@dlnk.dev

---
Generated by dLNk IDE Release Script
EOF

echo -e "${GREEN}✅ Release notes created${NC}"
echo ""

# Summary
echo "✨ Release Complete!"
echo "===================="
echo ""
echo "📦 Release directory: $RELEASE_VERSION_DIR"
echo ""
echo "📋 Contents:"
ls -lh "$RELEASE_VERSION_DIR" 2>/dev/null || echo "No files found"
echo ""
echo -e "${GREEN}🎉 Release v$VERSION ready for distribution!${NC}"
